/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  main                                   */
/*      FILE         :  main.c                                 */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include "common.h"
#include "./peripheral/GPIO.h"
#include "./peripheral/SCI7.h"
#include "./peripheral/CMT.h"


#ifdef CPPAPP
//Initialize global constructors
extern void __main()
{
  static int initialized;
  if (! initialized)
	{
	  typedef void (*pfunc) ();
	  extern pfunc __ctors[];
	  extern pfunc __ctors_end[];
	  pfunc *p;

	  initialized = 1;
	  for (p = __ctors_end; p > __ctors; )
	(*--p) ();

	}
}
#endif


int main(void) {

	volatile uint16 num = 8;
	volatile uint32 i = 0;
	uint8 *buf1 = "GR-KAEDE booting\r\n";
	uint8 *buf = "hello!\r\n";

	// uart_create(UART_9600);
	// uart_start();
	// SCI7_Serial_Send(buf1, 19);
	// uart_stop();

	uart_create(UART_9600);
	uart_start();
	SCI7_Serial_Send(buf, num);
//	uart_stop();


	while(1) {
		ms_wait(500);
		led_on(LED1);
		ms_wait(500);
		led_on(LED2);
		ms_wait(500);
		led_on(LED3);
		ms_wait(500);
		led_on(LED4);
		ms_wait(500);
		led_stop();
	}

return 0;
}


